# Generated by Django 3.1.7 on 2021-02-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_auto_20210227_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.errors'),
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
