# Generated by Django 3.1.7 on 2021-02-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20210227_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='errors',
            new_name='Questions',
        ),
    ]
